In [196]:
import pandas as pd
import matplotlib.pyplot as plt

In [197]:
dataset = pd.read_csv('California_Houses.csv')
dataset

Median_House_Value  Median_Income  Median_Age  Tot_Rooms  Tot_Bedrooms  \
0                452600.0         8.3252          41        880           129   
1                358500.0         8.3014          21       7099          1106   
2                352100.0         7.2574          52       1467           190   
3                341300.0         5.6431          52       1274           235   
4                342200.0         3.8462          52       1627           280   
...                   ...            ...         ...        ...           ...   
20635             78100.0         1.5603          25       1665           374   
20636             77100.0         2.5568          18        697           150   
20637             92300.0         1.7000          17       2254           485   
20638             84700.0         1.8672          18       1860           409   
20639             89400.0         2.3886          16       2785           616   

       Population  Households  Latitude  Longitude  Distance_to_coast  \
0             322         126     37.88    -122.23        9263.040773   
1            2401        1138     37.86    -122.22       10225.733072   
2             496         177     37.85    -122.24        8259.085109   
3             558         219     37.85    -122.25        7768.086571   
4             565         259     37.85    -122.25        7768.086571   
...           ...         ...       ...        ...                ...   
20635         845         330     39.48    -121.09      162031.481121   
20636         356         114     39.49    -121.21      160445.433537   
20637        1007         433     39.43    -121.22      153754.341182   
20638         741         349     39.43    -121.32      152005.022239   
20639        1387         530     39.37    -121.24      146866.196892   

       Distance_to_LA  Distance_to_SanDiego  Distance_to_SanJose  \
0       556529.158342         735501.806984         67432.517001   
1       554279.850069         733236.884360         65049.908574   
2       554610.717069         733525.682937         64867.289833   
3       555194.266086         734095.290744         65287.138412   
4       555194.266086         734095.290744         65287.138412   
...               ...                   ...                  ...   
20635   654530.186299         830631.543047        248510.058162   
20636   659747.068444         836245.915229        246849.888948   
20637   654042.214020         830699.573163        240172.220489   
20638   657698.007703         834672.461887        238193.865909   
20639   648723.337126         825569.179028        233282.769063   

       Distance_to_SanFrancisco  
0                  21250.213767  
1                  20880.600400  
2                  18811.487450  
3                  18031.047568  
4                  18031.047568  
...                         ...  
20635             222619.890417  
20636             218314.424634  
20637             212097.936232  
20638             207923.199166  
20639             205473.376575  

[20640 rows x 14 columns]

In [198]:
X = dataset.loc[:, 'Median_Income':].values
y = dataset.loc[:, 'Median_House_Value'].values

In [199]:
X

array([[8.32520000e+00, 4.10000000e+01, 8.80000000e+02, ...,
        7.35501807e+05, 6.74325170e+04, 2.12502138e+04],
       [8.30140000e+00, 2.10000000e+01, 7.09900000e+03, ...,
        7.33236884e+05, 6.50499086e+04, 2.08806004e+04],
       [7.25740000e+00, 5.20000000e+01, 1.46700000e+03, ...,
        7.33525683e+05, 6.48672898e+04, 1.88114874e+04],
       ...,
       [1.70000000e+00, 1.70000000e+01, 2.25400000e+03, ...,
        8.30699573e+05, 2.40172220e+05, 2.12097936e+05],
       [1.86720000e+00, 1.80000000e+01, 1.86000000e+03, ...,
        8.34672462e+05, 2.38193866e+05, 2.07923199e+05],
       [2.38860000e+00, 1.60000000e+01, 2.78500000e+03, ...,
        8.25569179e+05, 2.33282769e+05, 2.05473377e+05]])

In [200]:
y

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

In [201]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
sc.fit(X)
X = sc.transform(X)
sc.fit(y.reshape(-1,1))
y = sc.transform(y.reshape(-1,1))

In [202]:
X

array([[8.32520000e+00, 4.10000000e+01, 8.80000000e+02, ...,
        7.35501807e+05, 6.74325170e+04, 2.12502138e+04],
       [8.30140000e+00, 2.10000000e+01, 7.09900000e+03, ...,
        7.33236884e+05, 6.50499086e+04, 2.08806004e+04],
       [7.25740000e+00, 5.20000000e+01, 1.46700000e+03, ...,
        7.33525683e+05, 6.48672898e+04, 1.88114874e+04],
       ...,
       [1.70000000e+00, 1.70000000e+01, 2.25400000e+03, ...,
        8.30699573e+05, 2.40172220e+05, 2.12097936e+05],
       [1.86720000e+00, 1.80000000e+01, 1.86000000e+03, ...,
        8.34672462e+05, 2.38193866e+05, 2.07923199e+05],
       [2.38860000e+00, 1.60000000e+01, 2.78500000e+03, ...,
        8.25569179e+05, 2.33282769e+05, 2.05473377e+05]])

In [203]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.3,random_state=True)
X_test,X_val,y_test,y_val = train_test_split(X_test,y_test,test_size=0.5,random_state=True)
X_train.shape, X_test.shape, X_val.shape

((14448, 13), (3096, 13), (3096, 13))

In [204]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [205]:
y_pred = regressor.predict(X_test)
mse_linear = mean_squared_error(y_test, y_pred)
mae_linear = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mse_linear)
print('Mean Squared Error:', mae_linear)
print('accuracy using test:',regressor.score(X_test,y_test))
print('accuracy using train:',regressor.score(X_train,y_train))
print('accuracy using val:',regressor.score(X_val,y_val))

Mean Absolute Error: 4825653861.388197
Mean Squared Error: 50353.189505790106
accuracy using test: 0.6346950500393116
accuracy using train: 0.6493563065187331
accuracy using val: 0.6430792710669417


In [206]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=1,max_iter=100000)
lasso.fit(X_train,y_train)

Lasso(alpha=1, max_iter=100000)

In [207]:
y_pred = lasso.predict(X_test)
mse_lasso = mean_squared_error(y_test, y_pred)
mae_lasso = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae_lasso)
print('Mean Squared Error:', mse_lasso)
print('accuracy using test:',lasso.score(X_test,y_test))
print('accuracy using train:',lasso.score(X_train,y_train))
print('accuracy using val:',lasso.score(X_val,y_val))

Mean Absolute Error: 50353.29632497065
Mean Squared Error: 4825647135.845118
accuracy using test: 0.6346955591670378
accuracy using train: 0.6493563035648962
accuracy using val: 0.6430817957990611


In [208]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=1)
ridge.fit(X_train,y_train)

Ridge(alpha=1)

In [209]:
y_pred = ridge.predict(X_test)
mse_ridge = mean_squared_error(y_test, y_pred)
mae_ridge = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae_ridge)
print('Mean Squared Error:', mse_ridge)
print('accuracy using test:',ridge.score(X_test,y_test))
print('accuracy using train:',ridge.score(X_train,y_train))
print('accuracy using val:',ridge.score(X_val,y_val))

Mean Absolute Error: 50353.45858050672
Mean Squared Error: 4825631534.160269
accuracy using test: 0.6346967402241269
accuracy using train: 0.6493562807705838
accuracy using val: 0.6430860380586829


In [210]:
data = {
    'Model': ['linear', 'lasso', 'ridge'],
    'Mean Squared Error': [mse_linear, mse_lasso, mse_ridge],
    'Mean Absolute Error': [mae_linear, mae_lasso, mae_ridge]
}

df = pd.DataFrame(data)
print(df)

    Model  Mean Squared Error  Mean Absolute Error
0  linear        4.825654e+09         50353.189506
1   lasso        4.825647e+09         50353.296325
2   ridge        4.825632e+09         50353.458581
